#!/usr/bin/env python3
"""
Render a hiring/internship poster from a JSON job file to PNG.

Why this exists: every factual field on the poster (company, stipend, deadline,
job ID) has to be exactly right, so the text is drawn by a browser from real
data rather than generated by an image model. Nano Banana supplies only the
hero artwork, referenced from the JSON as hero.image.

Usage:
    python render_poster.py job.json -o poster.png
    python render_poster.py job.json -o poster.png --keep-html   # debug layout
    python render_poster.py job.json --browser "C:/path/to/chrome.exe"

Needs Pillow (pip install pillow) and any Chromium-family browser (Chrome,
Edge, Chromium) - it finds one automatically on Windows, macOS and Linux.

Headless Chrome reserves some of the requested window for window furniture,
so a screenshot at exactly the poster size loses a strip off the bottom and
pads it white. The amount varies by Chrome version, so rather than hardcode
an offset we render into a deliberately oversized window and crop the top
WxH region - correct on any version.
"""
import argparse, json, os, platform, shutil, subprocess, sys, tempfile
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("error: Pillow is required for exact poster dimensions.\n"
             "  pip install pillow      (or: python -m pip install pillow)")

HERE = Path(__file__).resolve().parent
OVERSHOOT = 240  # headroom for headless window furniture; cropped off afterwards
TEMPLATE = HERE / "template.html"

CANDIDATES = {
    "Windows": [
        r"C:\Program Files\Google\Chrome\Application\chrome.exe",
        r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
        r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
        r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
    ],
    "Darwin": [
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
        "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
        "/Applications/Chromium.app/Contents/MacOS/Chromium",
    ],
    "Linux": [
        "/opt/pw-browsers/chromium-1194/chrome-linux/chrome",
        "/usr/bin/google-chrome", "/usr/bin/chromium", "/usr/bin/chromium-browser",
    ],
}


def find_browser(explicit=None):
    if explicit:
        if Path(explicit).exists():
            return explicit
        sys.exit(f"error: --browser path does not exist: {explicit}")
    if os.environ.get("POSTER_BROWSER"):
        return os.environ["POSTER_BROWSER"]
    for name in ("chrome", "google-chrome", "chromium", "msedge", "microsoft-edge"):
        found = shutil.which(name)
        if found:
            return found
    for path in CANDIDATES.get(platform.system(), []):
        if Path(path).exists():
            return path
    # Playwright installs land in versioned dirs; take the newest.
    root = Path(os.environ.get("PLAYWRIGHT_BROWSERS_PATH", "/opt/pw-browsers"))
    if root.is_dir():
        hits = sorted(root.glob("chromium-*/chrome-linux/chrome"))
        if hits:
            return str(hits[-1])
    sys.exit(
        "error: no Chromium-family browser found.\n"
        "Install Google Chrome, or pass --browser with the full path to chrome.exe,\n"
        "or set the POSTER_BROWSER environment variable."
    )


def resolve_assets(data, base):
    """Rewrite hero/logo paths to absolute file URLs so the browser can load them.

    Paths in the JSON are read relative to the JSON file's own directory, which
    is what you want when a job file sits next to its nanobanana-output folder.
    """
    def fix(container, key):
        val = container.get(key)
        if not val or str(val).startswith(("http://", "https://", "data:", "file:")):
            return
        p = Path(val)
        if not p.is_absolute():
            p = (base / p).resolve()
        if not p.exists():
            print(f"warning: {key} not found, rendering without it: {p}", file=sys.stderr)
            container[key] = None
            return
        container[key] = p.as_uri()

    fix(data.setdefault("hero", {}), "image")
    fix(data.setdefault("brand", {}), "logo")
    return data


def main():
    ap = argparse.ArgumentParser(description="Render a hiring poster to PNG.")
    ap.add_argument("job", help="path to the job JSON file")
    ap.add_argument("-o", "--out", default="poster.png", help="output PNG path")
    ap.add_argument("--width", type=int, default=1080)
    ap.add_argument("--height", type=int, default=1350)
    ap.add_argument("--browser", help="explicit path to a Chromium-family binary")
    ap.add_argument("--keep-html", action="store_true",
                    help="keep the generated HTML next to the PNG for layout debugging")
    args = ap.parse_args()

    job_path = Path(args.job).resolve()
    if not job_path.exists():
        sys.exit(f"error: job file not found: {job_path}")
    try:
        data = json.loads(job_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        sys.exit(f"error: {job_path.name} is not valid JSON: {e}")

    data = resolve_assets(data, job_path.parent)
    size = data.get("size") or {}
    width, height = int(size.get("w", args.width)), int(size.get("h", args.height))

    html = TEMPLATE.read_text(encoding="utf-8")
    html = html.replace("__POSTER_DATA__", json.dumps(data, ensure_ascii=False))
    html = html.replace("width:1080px; height:1350px", f"width:{width}px; height:{height}px")

    out = Path(args.out).resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    html_path = out.with_suffix(".html") if args.keep_html else Path(
        tempfile.mkstemp(suffix=".html")[1])
    html_path.write_text(html, encoding="utf-8")

    browser = find_browser(args.browser)
    profile = tempfile.mkdtemp(prefix="poster-profile-")
    cmd = [
        browser, "--headless=new", "--disable-gpu", "--hide-scrollbars",
        "--force-device-scale-factor=1", "--no-sandbox",
        f"--user-data-dir={profile}",
        f"--window-size={width},{height + OVERSHOOT}",
        f"--screenshot={out}",
        html_path.as_uri(),
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    if not out.exists():
        sys.exit(f"error: browser produced no image.\n{proc.stderr.strip()[:1500]}")

    img = Image.open(out)
    if img.size != (width, height):
        img.convert("RGB").crop((0, 0, width, height)).save(out, optimize=True)

    shutil.rmtree(profile, ignore_errors=True)
    if not args.keep_html:
        # On Windows the browser process can still hold the HTML open for a
        # moment after the screenshot lands, and unlink() then raises WinError
        # 32 *after* the poster has already been written correctly. Exiting
        # non-zero there tells any automation the render failed when it did
        # not, so a stranded temp file is the lesser problem and is swept up
        # by the OS.
        try:
            html_path.unlink(missing_ok=True)
        except OSError:
            pass
    print(f"{out}  ({width}x{height}, {out.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
