'use strict';

/**
 * Document History has to say who made each document.
 *
 * Every row in the HR portal's history read "Automation", including documents
 * an HR user generated by hand. The cause was one over-eager pattern: the
 * method was inferred with /auto|system|cron/ against `sentBy`, and "System" is
 * the placeholder four different generate paths write there. So the word
 * "System" — which means "we did not record who" — was read as "a cron did it".
 *
 * These tests pin the replacement rule: automation has to be stated, not
 * implied.
 */

const DocumentHistory = require('../../models/DocumentHistory');
const resolveMethod = DocumentHistory.resolveMethod.bind(DocumentHistory);

describe('an explicit method always wins', () => {
  it('keeps manual even when sentBy mentions automation', () => {
    expect(resolveMethod('manual', 'Auto System')).toBe('manual');
  });

  it('keeps automation even when sentBy names a person', () => {
    expect(resolveMethod('automation', 'HR Portal (Priya)')).toBe('automation');
  });

  it('ignores a value that is neither', () => {
    expect(resolveMethod('something-else', 'HR Portal')).toBe('manual');
  });
});

describe('the scheduled jobs are recognised as automation', () => {
  it.each([
    'Auto System',
    'System Automation',
    'automation',
    'AUTO-CRON',
    'cron',
    'Scheduled job'
  ])('%s', (sentBy) => {
    expect(resolveMethod(undefined, sentBy)).toBe('automation');
  });
});

describe('a person acting through the portal is manual', () => {
  it('treats the bare "System" placeholder as manual', () => {
    // This is the one that mattered. "System" is the default `sentBy` on
    // generateAndSaveCert and three other paths; it records that nobody wrote
    // down who did it, not that a cron did.
    expect(resolveMethod(undefined, 'System')).toBe('manual');
  });

  it.each([
    'HR Portal',
    'HR Portal (Manual)',
    'HR Portal (Forced)',
    'HR Portal (priya@ten.com)',
    'admin',
    '',
    undefined,
    null
  ])('%p', (sentBy) => {
    expect(resolveMethod(undefined, sentBy)).toBe('manual');
  });
});

describe('the pattern matches whole words, not fragments', () => {
  it('does not read "Autonomous Systems College" as a cron', () => {
    expect(resolveMethod(undefined, 'HR Portal (Autonomous Systems College)')).toBe('manual');
  });

  it('still catches automation at the start, middle and end', () => {
    expect(resolveMethod(undefined, 'automation ran this')).toBe('automation');
    expect(resolveMethod(undefined, 'nightly cron job')).toBe('automation');
    expect(resolveMethod(undefined, 'issued by auto')).toBe('automation');
  });
});
