/**
 * TEN curriculum, generated from the Ten-Ecosystem repo.
 *
 * Source: seeds/domainTasks.seed.js in
 * github.com/the-Entrepreneurship-Network/Ten-Ecosystem1 - 644 rows, parsed
 * rather than retyped so the weeks, coin values and difficulty ratings are
 * the platform's own and cannot drift from it by transcription.
 *
 * Regenerate rather than hand-edit.
 */

export type Difficulty = "easy" | "medium" | "hard" | "expert";
export type DurationKey = "1month" | "45days" | "3months" | "6months";

/** [week, title, description, coinReward, difficulty] */
export type WeekTask = [number, string, string, number, Difficulty];

export const CURRICULUM: Record<string, Partial<Record<DurationKey, WeekTask[]>>> = {
  "Python Development": {
    "3months": [
      [1, "Python Basics", "Write 10 Python programs covering variables, data types, and input/output", 20, "easy"],
      [2, "Control Flow", "Build a number guessing game using loops, conditionals, and functions", 20, "easy"],
      [3, "Data Structures", "Build a contact book application using lists and dictionaries", 25, "easy"],
      [4, "File Handling", "Build a student grade tracker that reads and writes to files", 25, "medium"],
      [5, "OOP", "Design a full library management system using classes and inheritance", 30, "medium"],
      [6, "APIs & Modules", "Build a weather dashboard using OpenWeatherMap API", 30, "medium"],
      [7, "Databases", "Build a to-do app with full SQLite CRUD backend", 35, "medium"],
      [8, "Web Scraping", "Scrape a job listings site and store results in a CSV file", 35, "hard"],
      [9, "Flask Basics", "Build a simple REST API with two endpoints using Flask", 40, "hard"],
      [10, "REST API", "Build a full CRUD REST API with Flask and SQLite", 40, "hard"],
      [11, "Mini Project", "Build a student management system with a Flask backend", 50, "hard"],
      [12, "Final Project", "Deploy a complete Flask application to Render with a live database", 100, "expert"],
    ],
    "6months": [
      [1, "Python Basics", "Write 10 Python programs covering variables, data types, and input/output", 20, "easy"],
      [2, "Control Flow", "Build a number guessing game using loops, conditionals, and functions", 20, "easy"],
      [3, "Data Structures", "Build a contact book application using lists and dictionaries", 25, "easy"],
      [4, "File Handling", "Build a student grade tracker that reads and writes to files", 25, "medium"],
      [5, "OOP", "Design a full library management system using classes and inheritance", 30, "medium"],
      [6, "APIs & Modules", "Build a weather dashboard using OpenWeatherMap API", 30, "medium"],
      [7, "Databases", "Build a to-do app with full SQLite CRUD backend", 35, "medium"],
      [8, "Web Scraping", "Scrape a job listings site and store results in a CSV file", 35, "hard"],
      [9, "Flask Basics", "Build a simple REST API with two endpoints using Flask", 40, "hard"],
      [10, "REST API", "Build a full CRUD REST API with Flask and SQLite", 40, "hard"],
      [11, "Mini Project", "Build a student management system with a Flask backend", 50, "hard"],
      [12, "Final Project", "Deploy a complete Flask application to Render with a live database", 100, "expert"],
      [13, "Advanced Python", "Implement decorators, generators, and context managers in a real project", 40, "hard"],
      [14, "Data Analysis", "Pandas + NumPy project: analyse a real-world dataset and produce insights", 45, "hard"],
      [15, "Visualisation", "Build a Matplotlib + Seaborn dashboard with 6 chart types", 45, "hard"],
      [16, "ML Intro", "Train and evaluate a classification model using Scikit-learn", 50, "expert"],
      [17, "Async Python", "Build an asynchronous web scraper using asyncio and aiohttp", 50, "expert"],
      [18, "Testing", "Write complete unit tests for a previous project using pytest", 45, "hard"],
      [19, "Docker", "Containerise your Flask application using Docker and Docker Compose", 55, "expert"],
      [20, "CI/CD", "Set up a GitHub Actions pipeline with automated testing and deployment", 55, "expert"],
      [21, "Advanced API", "Build a production-grade REST API with JWT auth and rate limiting", 60, "expert"],
      [22, "System Design", "Design a scalable Python backend architecture — document and diagram it", 60, "expert"],
      [23, "Capstone Planning", "Plan, scaffold, and document the final capstone project with full architecture", 50, "expert"],
      [24, "Final Capstone", "Complete and deploy a production-ready Python application with full documentation", 200, "expert"],
    ],
    "45days": [
      [1, "Basics + Control Flow", "Write 15 programs covering Python syntax, loops, conditionals, and functions", 22, "easy"],
      [2, "Data Structures + File Handling", "Build a contact manager application with full file persistence", 27, "medium"],
      [3, "OOP + Modules", "Design a library management system using classes, inheritance, and external modules", 33, "medium"],
      [4, "APIs + Database", "Weather app using a public API and a SQLite to-do backend in the same project", 38, "hard"],
      [5, "Flask + REST API", "Build a full CRUD REST API with Flask and SQLite — test all endpoints", 44, "hard"],
      [6, "Mini + Final Project", "Complete and deploy a Flask application to a live server with a real database", 110, "expert"],
    ],
    "1month": [
      [1, "Python Fundamentals", "Master variables, loops, and functions — write 12 programs covering each concept", 25, "easy"],
      [2, "Data Structures + OOP", "Build a contact book using dictionaries and a class-based system for managing entries", 30, "medium"],
      [3, "APIs", "Connect to a public API and display live data in the terminal with error handling", 35, "medium"],
      [4, "Final Mini Project", "Build a documented Python project with a README and publish it to a GitHub repo", 75, "hard"],
    ],
  },
  "Java Development": {
    "3months": [
      [1, "Java Basics", "Write 10 programs covering variables, operators, and input/output in Java", 20, "easy"],
      [2, "Control Flow", "Build a calculator application using switch statements and loops", 20, "easy"],
      [3, "OOP", "Design a bank account system using classes, constructors, and inheritance", 25, "easy"],
      [4, "Collections", "Build an inventory management system using ArrayList and HashMap", 25, "medium"],
      [5, "File Handling", "Student record system with file I/O and exception handling", 30, "medium"],
      [6, "JDBC", "Connect Java to MySQL and build a full CRUD console application", 35, "medium"],
      [7, "Mini Project 1", "Console-based library management system with full CRUD operations", 40, "hard"],
      [8, "Spring Boot", "Build your first Spring Boot REST API with two working endpoints", 40, "hard"],
      [9, "Spring CRUD", "Full CRUD operations with Spring Boot and MySQL database", 45, "hard"],
      [10, "Auth + Testing", "Add JWT authentication and test all endpoints in Postman", 45, "hard"],
      [11, "Mini Project 2", "Employee management REST API with full CRUD and authentication", 50, "hard"],
      [12, "Final Project", "Complete backend system with full documentation and deployment", 100, "expert"],
    ],
    "6months": [
      [1, "Java Basics", "Write 10 programs covering variables, operators, and input/output in Java", 20, "easy"],
      [2, "Control Flow", "Build a calculator application using switch statements and loops", 20, "easy"],
      [3, "OOP", "Design a bank account system using classes, constructors, and inheritance", 25, "easy"],
      [4, "Collections", "Build an inventory management system using ArrayList and HashMap", 25, "medium"],
      [5, "File Handling", "Student record system with file I/O and exception handling", 30, "medium"],
      [6, "JDBC", "Connect Java to MySQL and build a full CRUD console application", 35, "medium"],
      [7, "Mini Project 1", "Console-based library management system with full CRUD operations", 40, "hard"],
      [8, "Spring Boot", "Build your first Spring Boot REST API with two working endpoints", 40, "hard"],
      [9, "Spring CRUD", "Full CRUD operations with Spring Boot and MySQL database", 45, "hard"],
      [10, "Auth + Testing", "Add JWT authentication and test all endpoints in Postman", 45, "hard"],
      [11, "Mini Project 2", "Employee management REST API with full CRUD and authentication", 50, "hard"],
      [12, "Final Project", "Complete backend system with full documentation and deployment", 100, "expert"],
      [13, "Advanced OOP", "Implement advanced design patterns: Abstract Factory, Builder, and Composite", 40, "hard"],
      [14, "Multithreading", "Build a thread-safe bank account simulator using Java concurrency", 45, "hard"],
      [15, "Microservices Intro", "Split a monolith application into two separate Spring Boot microservices", 50, "expert"],
      [16, "Kafka Basics", "Implement asynchronous messaging between two services using Apache Kafka", 50, "expert"],
      [17, "Unit Testing", "JUnit 5 + Mockito: write full test coverage for a Spring Boot service", 45, "hard"],
      [18, "Security", "Spring Security: implement OAuth2 and JWT authentication in a full application", 55, "expert"],
      [19, "Docker", "Containerise the Spring Boot app and MySQL database with Docker Compose", 55, "expert"],
      [20, "Kubernetes", "Deploy the containerised application to a local Kubernetes cluster", 60, "expert"],
      [21, "CI/CD", "GitHub Actions pipeline: build, test, and deploy the Java application automatically", 60, "expert"],
      [22, "Performance", "Identify and fix N+1 query problems, then add Redis caching to the application", 60, "expert"],
      [23, "System Design", "Design a high-level architecture for a Twitter-like social media backend", 55, "expert"],
      [24, "Final Capstone", "Complete a production-grade Java backend with full documentation and deployment", 200, "expert"],
    ],
    "45days": [
      [1, "Basics + Control Flow", "Write 12 programs covering variables, calculator logic, and switch statements", 22, "easy"],
      [2, "OOP + Collections", "Bank account system using classes plus inventory management with ArrayList and HashMap", 27, "medium"],
      [3, "File Handling + JDBC", "Student records with file I/O exception handling and MySQL database connection", 38, "medium"],
      [4, "Mini Project 1 + Spring", "Console library system plus your first Spring Boot REST endpoint", 44, "hard"],
      [5, "Spring CRUD + Auth", "Full CRUD API with Spring Boot and JWT authentication implemented", 49, "hard"],
      [6, "Mini Project 2 + Final", "Employee management REST API plus a fully deployed backend project", 110, "expert"],
    ],
    "1month": [
      [1, "Java Basics + OOP", "Write 10 programs covering syntax and OOP — build a simple class-based bank system", 25, "easy"],
      [2, "Collections + File I/O", "Inventory system using ArrayList and HashMap with file-based record storage", 30, "medium"],
      [3, "Spring Boot Intro", "Build a REST API with 3 working endpoints using Spring Boot", 35, "hard"],
      [4, "Final Mini Project", "Documented Java backend project published to a GitHub repository", 75, "hard"],
    ],
  },
  "DevOps with AWS": {
    "3months": [
      [1, "Linux Basics", "Complete 20 command-line exercises covering navigation, file permissions, and processes", 20, "easy"],
      [2, "Shell Scripting", "Write 5 automation shell scripts for real tasks: backup, user creation, and monitoring", 25, "easy"],
      [3, "Git & GitHub", "Create a project repo, document a branching strategy, and set up a PR workflow", 25, "easy"],
      [4, "Mini Project 1", "Build an auto-deploy script using Shell scripting and Git hooks", 35, "medium"],
      [5, "CI/CD Concepts", "Install Jenkins and configure a basic build job for a sample application", 30, "medium"],
      [6, "CI/CD Pipeline", "Create a full CI pipeline that builds, tests, and packages an application", 35, "medium"],
      [7, "Docker", "Build and run Docker containers, write a Dockerfile for a web application", 40, "hard"],
      [8, "Mini Project 2", "Containerise an application and deploy it using Docker Compose", 45, "hard"],
      [9, "AWS Basics", "Launch an EC2 instance, host a static site on S3, and configure IAM roles", 45, "hard"],
      [10, "Kubernetes", "Deploy pods, services, and deployments on a local Minikube cluster", 50, "expert"],
      [11, "Terraform", "Write Infrastructure as Code to provision an EC2 instance and S3 bucket", 50, "expert"],
      [12, "Final Project", "Complete end-to-end CI/CD pipeline: Docker + Kubernetes + AWS + monitoring", 100, "expert"],
    ],
    "6months": [
      [1, "Linux Basics", "Complete 20 command-line exercises covering navigation, file permissions, and processes", 20, "easy"],
      [2, "Shell Scripting", "Write 5 automation shell scripts for real tasks: backup, user creation, and monitoring", 25, "easy"],
      [3, "Git & GitHub", "Create a project repo, document a branching strategy, and set up a PR workflow", 25, "easy"],
      [4, "Mini Project 1", "Build an auto-deploy script using Shell scripting and Git hooks", 35, "medium"],
      [5, "CI/CD Concepts", "Install Jenkins and configure a basic build job for a sample application", 30, "medium"],
      [6, "CI/CD Pipeline", "Create a full CI pipeline that builds, tests, and packages an application", 35, "medium"],
      [7, "Docker", "Build and run Docker containers, write a Dockerfile for a web application", 40, "hard"],
      [8, "Mini Project 2", "Containerise an application and deploy it using Docker Compose", 45, "hard"],
      [9, "AWS Basics", "Launch an EC2 instance, host a static site on S3, and configure IAM roles", 45, "hard"],
      [10, "Kubernetes", "Deploy pods, services, and deployments on a local Minikube cluster", 50, "expert"],
      [11, "Terraform", "Write Infrastructure as Code to provision an EC2 instance and S3 bucket", 50, "expert"],
      [12, "Final Project", "Complete end-to-end CI/CD pipeline: Docker + Kubernetes + AWS + monitoring", 100, "expert"],
      [13, "Advanced Networking", "Set up VPC, subnets, and a NAT gateway on AWS with proper security groups", 45, "hard"],
      [14, "Monitoring", "Set up Prometheus and Grafana dashboards for a running application", 50, "expert"],
      [15, "Logging", "Centralised logging with ELK Stack: Elasticsearch, Logstash, and Kibana", 50, "expert"],
      [16, "Security in DevOps", "Implement SAST security scanning in the CI/CD pipeline", 50, "expert"],
      [17, "Advanced Kubernetes", "Helm charts, ConfigMaps, Secrets, and HPA autoscaling on a cluster", 55, "expert"],
      [18, "Service Mesh", "Implement Istio service mesh on a Kubernetes cluster", 60, "expert"],
      [19, "Ansible", "Write Ansible playbooks to provision and configure multiple servers", 55, "expert"],
      [20, "Cost Optimisation", "Analyse AWS costs and implement rightsizing and reserved instance recommendations", 50, "expert"],
      [21, "GitOps", "Implement ArgoCD for GitOps-based continuous deployments", 60, "expert"],
      [22, "Disaster Recovery", "Design and test a complete disaster recovery plan for a cloud application", 60, "expert"],
      [23, "Capstone Planning", "Plan a full end-to-end DevOps pipeline for a real application — document and diagram", 55, "expert"],
      [24, "Final Capstone", "Complete DevOps pipeline: code → build → test → deploy → monitor — fully documented", 200, "expert"],
    ],
    "45days": [
      [1, "Linux + Shell Scripting", "Complete 15 Linux command-line exercises and write 3 automation shell scripts", 27, "easy"],
      [2, "Git + Mini Project 1", "Set up a branching workflow on GitHub and build an auto-deploy script with Git hooks", 33, "medium"],
      [3, "CI/CD Concepts + Pipeline", "Install Jenkins, configure a build job, and create a full CI pipeline", 38, "medium"],
      [4, "Docker + Mini Project 2", "Build Docker containers and deploy an application with Docker Compose", 44, "hard"],
      [5, "AWS + Kubernetes", "Launch EC2/S3/IAM on AWS and deploy pods and services on Minikube", 49, "hard"],
      [6, "Terraform + Final", "Write IaC for AWS infrastructure and complete the end-to-end CI/CD pipeline", 110, "expert"],
    ],
    "1month": [
      [1, "Linux + Shell", "20 Linux command exercises and 3 automation shell scripts", 25, "easy"],
      [2, "Git + CI/CD Intro", "GitHub branching workflow and a basic Jenkins CI job for a sample app", 30, "medium"],
      [3, "Docker", "Containerise an application — write a Dockerfile and run it with Docker Compose", 35, "hard"],
      [4, "Final Mini Project", "Deploy a containerised app to AWS EC2 and document the process end-to-end", 75, "hard"],
    ],
  },
  "Web Development": {
    "3months": [
      [1, "HTML Foundations", "Build the full structure of a personal portfolio site in HTML", 20, "easy"],
      [2, "CSS Styling", "Style the portfolio using Flexbox, Grid, and custom CSS properties", 20, "easy"],
      [3, "JavaScript Basics", "Add 5 interactive features to the portfolio using vanilla JavaScript", 25, "easy"],
      [4, "DOM + Events", "Build a dynamic to-do list application with localStorage persistence", 25, "medium"],
      [5, "Responsive Design", "Make the portfolio pixel-perfect on all screen sizes using media queries", 30, "medium"],
      [6, "Deployment", "Deploy the portfolio to GitHub Pages with a custom domain configured", 30, "medium"],
      [7, "React Basics", "Build a React component library with 8 reusable components", 35, "medium"],
      [8, "React Hooks", "Build a weather app using useState, useEffect, and custom hooks", 35, "hard"],
      [9, "React Router", "Build a multi-page React application with protected routes", 40, "hard"],
      [10, "API Integration", "Connect your React application to a public REST API with loading and error states", 40, "hard"],
      [11, "Mini Project", "Full-featured React web application with routing, state management, and API integration", 50, "hard"],
      [12, "Final Project", "Deploy a complete web application to Vercel with a live domain", 100, "expert"],
    ],
    "6months": [
      [1, "HTML Foundations", "Build the full structure of a personal portfolio site in HTML", 20, "easy"],
      [2, "CSS Styling", "Style the portfolio using Flexbox, Grid, and custom CSS properties", 20, "easy"],
      [3, "JavaScript Basics", "Add 5 interactive features to the portfolio using vanilla JavaScript", 25, "easy"],
      [4, "DOM + Events", "Build a dynamic to-do list application with localStorage persistence", 25, "medium"],
      [5, "Responsive Design", "Make the portfolio pixel-perfect on all screen sizes using media queries", 30, "medium"],
      [6, "Deployment", "Deploy the portfolio to GitHub Pages with a custom domain configured", 30, "medium"],
      [7, "React Basics", "Build a React component library with 8 reusable components", 35, "medium"],
      [8, "React Hooks", "Build a weather app using useState, useEffect, and custom hooks", 35, "hard"],
      [9, "React Router", "Build a multi-page React application with protected routes", 40, "hard"],
      [10, "API Integration", "Connect your React application to a public REST API with loading and error states", 40, "hard"],
      [11, "Mini Project", "Full-featured React web application with routing, state management, and API integration", 50, "hard"],
      [12, "Final Project", "Deploy a complete web application to Vercel with a live domain", 100, "expert"],
      [13, "TypeScript", "Rewrite a previous React project fully in TypeScript with proper type definitions", 40, "hard"],
      [14, "Next.js", "Build a full server-side rendered blog using Next.js App Router", 45, "hard"],
      [15, "State Management", "Implement Zustand or Redux Toolkit for managing complex application state", 50, "expert"],
      [16, "Performance", "Lighthouse audit and fix: implement lazy loading, code splitting, and caching", 50, "expert"],
      [17, "Testing", "Playwright end-to-end tests for the full web application", 50, "expert"],
      [18, "Accessibility", "WCAG 2.1 audit and fix all accessibility issues in the application", 45, "hard"],
      [19, "Web Security", "Implement CSP, CORS, and XSS prevention on a production web application", 55, "expert"],
      [20, "PWA", "Convert an existing web app to a Progressive Web App with full offline support", 55, "expert"],
      [21, "Web3 Basics", "Build a wallet connect page using Ethers.js as an introduction to Web3", 60, "expert"],
      [22, "Animation", "Advanced Framer Motion: page transitions and scroll-triggered animations", 50, "hard"],
      [23, "Capstone Planning", "Plan and scaffold a production-quality full-stack web application", 50, "expert"],
      [24, "Final Capstone", "Complete and deploy a full production web application with documentation", 200, "expert"],
    ],
    "45days": [
      [1, "HTML + CSS", "Build and fully style a personal portfolio site using Flexbox and Grid", 22, "easy"],
      [2, "JavaScript + DOM", "Add 5 interactive features to the portfolio and build a dynamic to-do list", 27, "medium"],
      [3, "Responsive + Deploy", "Make the portfolio mobile-responsive and deploy it to GitHub Pages", 33, "medium"],
      [4, "React Basics + Hooks", "Build an 8-component library plus a weather app using React hooks", 38, "hard"],
      [5, "React Router + API", "Multi-page React app with protected routes connected to a live REST API", 44, "hard"],
      [6, "Final Project", "Deploy a complete React web application to Vercel", 110, "expert"],
    ],
    "1month": [
      [1, "HTML + CSS", "Build and style a personal portfolio site", 25, "easy"],
      [2, "JavaScript + DOM", "Dynamic to-do list with full localStorage state management", 30, "medium"],
      [3, "React Basics", "Build 6 reusable components using useState and props", 35, "medium"],
      [4, "Final Mini Project", "React app deployed to Vercel with a GitHub repository and README", 75, "hard"],
    ],
  },
  "MERN Stack Development": {
    "3months": [
      [1, "MongoDB", "Set up Atlas, create collections, and perform CRUD operations via Compass and code", 20, "easy"],
      [2, "Express.js", "Build a basic REST API with 4 working routes using Express", 25, "easy"],
      [3, "React Foundations", "Build 8 reusable React components with props and state management", 25, "easy"],
      [4, "Backend API", "Full CRUD Node/Express API connected to MongoDB Atlas", 30, "medium"],
      [5, "Full Stack Connect", "Connect React frontend to Express backend via Axios with proper error handling", 30, "medium"],
      [6, "Authentication", "JWT authentication with register, login, and protected routes", 35, "medium"],
      [7, "State Management", "Implement Redux Toolkit or Context API for global state across the application", 35, "hard"],
      [8, "File Uploads", "Image upload with Multer on the backend and proper file handling", 40, "hard"],
      [9, "Real-time Features", "Add Socket.io for live notifications or real-time chat features", 45, "hard"],
      [10, "Testing", "Jest + React Testing Library: write tests for components and API endpoints", 45, "hard"],
      [11, "Mini Project", "Full-stack blog platform with authentication, posts, and comments", 55, "hard"],
      [12, "Final Project", "Deploy complete MERN app to Vercel (frontend) and Railway (backend)", 100, "expert"],
    ],
    "6months": [
      [1, "MongoDB", "Set up Atlas, create collections, and perform CRUD operations via Compass and code", 20, "easy"],
      [2, "Express.js", "Build a basic REST API with 4 working routes using Express", 25, "easy"],
      [3, "React Foundations", "Build 8 reusable React components with props and state management", 25, "easy"],
      [4, "Backend API", "Full CRUD Node/Express API connected to MongoDB Atlas", 30, "medium"],
      [5, "Full Stack Connect", "Connect React frontend to Express backend via Axios with proper error handling", 30, "medium"],
      [6, "Authentication", "JWT authentication with register, login, and protected routes", 35, "medium"],
      [7, "State Management", "Implement Redux Toolkit or Context API for global state across the application", 35, "hard"],
      [8, "File Uploads", "Image upload with Multer on the backend and proper file handling", 40, "hard"],
      [9, "Real-time Features", "Add Socket.io for live notifications or real-time chat features", 45, "hard"],
      [10, "Testing", "Jest + React Testing Library: write tests for components and API endpoints", 45, "hard"],
      [11, "Mini Project", "Full-stack blog platform with authentication, posts, and comments", 55, "hard"],
      [12, "Final Project", "Deploy complete MERN app to Vercel (frontend) and Railway (backend)", 100, "expert"],
      [13, "TypeScript MERN", "Add TypeScript to both the React frontend and Express backend", 40, "hard"],
      [14, "GraphQL", "Replace the REST API with GraphQL using Apollo Server and Apollo Client", 50, "expert"],
      [15, "Microservices", "Split the MERN application into two separate backend microservices", 50, "expert"],
      [16, "Redis Caching", "Add a Redis caching layer to the Express API for frequently accessed data", 50, "expert"],
      [17, "WebSockets", "Build a full real-time chat application using Socket.io with rooms", 55, "expert"],
      [18, "Testing", "Supertest for API testing plus Jest for React component testing", 50, "expert"],
      [19, "Docker", "Dockerise the full MERN stack with a docker-compose configuration", 55, "expert"],
      [20, "CI/CD", "GitHub Actions pipeline: test, build, and deploy the MERN application", 55, "expert"],
      [21, "Rate Limiting", "Add rate limiting, helmet security headers, and input sanitisation", 50, "hard"],
      [22, "Search", "Implement full-text search using MongoDB Atlas Search", 55, "expert"],
      [23, "Capstone Planning", "Plan and document a full-stack SaaS product — architecture, wireframes, DB schema", 55, "expert"],
      [24, "Final Capstone", "Complete and deploy a production MERN SaaS application", 200, "expert"],
    ],
    "45days": [
      [1, "MongoDB + Express", "Set up Atlas, perform CRUD, and build a 4-route REST API with Express", 27, "easy"],
      [2, "React + Full Stack", "Build 8 React components and connect the frontend to the Express backend", 33, "medium"],
      [3, "Auth + State", "JWT authentication with register/login and Redux Toolkit global state", 38, "medium"],
      [4, "File Upload + Socket", "Multer file uploads and Socket.io real-time chat in the same project", 44, "hard"],
      [5, "Testing + Mini Project", "Jest tests for components and API plus a full-stack blog platform", 49, "hard"],
      [6, "Final Project", "Deploy complete MERN stack application to Vercel and Railway", 110, "expert"],
    ],
    "1month": [
      [1, "MongoDB + Express", "Atlas setup, CRUD operations, and a basic Express REST API", 25, "easy"],
      [2, "React + Full Stack", "React component library connected to the Express backend via Axios", 30, "medium"],
      [3, "Authentication", "JWT register/login with protected routes on both frontend and backend", 35, "hard"],
      [4, "Final Mini Project", "Complete MERN application deployed with README and GitHub repository", 75, "hard"],
    ],
  },
  "Data Science": {
    "3months": [
      [1, "Python for DS", "NumPy array operations + Pandas DataFrame exercises: complete 30 hands-on tasks", 20, "easy"],
      [2, "Data Cleaning", "Download a messy Kaggle dataset and clean it completely — handle nulls, types, outliers", 25, "easy"],
      [3, "EDA", "Exploratory data analysis: produce 10 visualisations with written insights", 25, "medium"],
      [4, "Visualisation", "Build a data dashboard with 6 different chart types using Matplotlib and Seaborn", 30, "medium"],
      [5, "Statistics", "Apply descriptive and inferential statistics to a real-world dataset", 30, "medium"],
      [6, "ML Fundamentals", "Train and evaluate a linear regression model on a structured dataset", 35, "medium"],
      [7, "Classification", "Build a decision tree and SVM classifier, then compare accuracy metrics", 35, "hard"],
      [8, "Model Evaluation", "Apply cross-validation, confusion matrix, and ROC curve analysis to models", 40, "hard"],
      [9, "Feature Engineering", "Feature selection and dimensionality reduction using PCA and filter methods", 40, "hard"],
      [10, "NLP Basics", "Sentiment analysis on a real Twitter or Reddit dataset using NLTK and sklearn", 45, "hard"],
      [11, "Mini Project", "End-to-end ML pipeline on a Kaggle competition dataset with full documentation", 55, "expert"],
      [12, "Final Project", "Data science report plus model deployed as a live Streamlit application", 100, "expert"],
    ],
    "6months": [
      [1, "Python for DS", "NumPy array operations + Pandas DataFrame exercises: complete 30 hands-on tasks", 20, "easy"],
      [2, "Data Cleaning", "Download a messy Kaggle dataset and clean it completely", 25, "easy"],
      [3, "EDA", "Exploratory data analysis: produce 10 visualisations with written insights", 25, "medium"],
      [4, "Visualisation", "Build a data dashboard with 6 different chart types", 30, "medium"],
      [5, "Statistics", "Apply descriptive and inferential statistics to a real-world dataset", 30, "medium"],
      [6, "ML Fundamentals", "Train and evaluate a linear regression model on a structured dataset", 35, "medium"],
      [7, "Classification", "Build a decision tree and SVM classifier, then compare accuracy", 35, "hard"],
      [8, "Model Evaluation", "Cross-validation, confusion matrix, and ROC curve analysis", 40, "hard"],
      [9, "Feature Engineering", "Feature selection and dimensionality reduction", 40, "hard"],
      [10, "NLP Basics", "Sentiment analysis on a real social media dataset", 45, "hard"],
      [11, "Mini Project", "End-to-end ML pipeline on a Kaggle dataset", 55, "expert"],
      [12, "Final Project", "Data science report and model deployed as a Streamlit app", 100, "expert"],
      [13, "Deep Learning Intro", "Build a neural network from scratch with TensorFlow/Keras on a classification task", 50, "expert"],
      [14, "Computer Vision", "Image classification using CNN on the CIFAR-10 dataset", 55, "expert"],
      [15, "Time Series", "Forecast stock prices using LSTM neural networks", 55, "expert"],
      [16, "Recommendation Systems", "Build a movie recommendation engine using collaborative filtering", 55, "expert"],
      [17, "MLOps Basics", "MLflow: track experiments, version models, and compare runs", 55, "expert"],
      [18, "Model Deployment", "Deploy an ML model as a production REST API using FastAPI", 60, "expert"],
      [19, "Big Data Intro", "PySpark: process a dataset too large for Pandas on a local cluster", 60, "expert"],
      [20, "AutoML", "Compare AutoML tools: H2O and AutoSklearn on the same dataset", 55, "expert"],
      [21, "Explainable AI", "SHAP values: explain and visualise model predictions for stakeholders", 55, "expert"],
      [22, "Data Pipeline", "Build an end-to-end ETL pipeline using Apache Airflow", 60, "expert"],
      [23, "Capstone Planning", "Plan a full data science product from raw data to deployed dashboard", 55, "expert"],
      [24, "Final Capstone", "Complete DS project: data → model → REST API → dashboard — fully documented", 200, "expert"],
    ],
    "45days": [
      [1, "Python for DS + Cleaning", "NumPy/Pandas exercises plus clean a real Kaggle dataset end to end", 27, "easy"],
      [2, "EDA + Visualisation", "10 visualisations with insights plus a 6-chart-type dashboard", 33, "medium"],
      [3, "Statistics + ML Basics", "Statistical analysis and train a linear regression model with evaluation", 38, "medium"],
      [4, "Classification + Evaluation", "Decision tree model plus confusion matrix and ROC curve analysis", 44, "hard"],
      [5, "Feature Engineering + NLP", "Feature selection techniques plus sentiment analysis on social media data", 49, "hard"],
      [6, "Final Project", "End-to-end ML pipeline plus model deployed on Streamlit", 110, "expert"],
    ],
    "1month": [
      [1, "Python for DS", "Pandas and NumPy: clean and explore a Kaggle dataset", 25, "easy"],
      [2, "Visualisation", "Produce 8 visualisations with written insights on the same dataset", 30, "medium"],
      [3, "ML Basics", "Train a linear regression model and evaluate it with RMSE and R²", 35, "medium"],
      [4, "Final Project", "End-to-end Jupyter notebook: data → model → insights report with visuals", 75, "hard"],
    ],
  },
  "Cyber Security": {
    "3months": [
      [1, "Security Fundamentals", "Write a detailed report on CIA Triad, common attack types, and threat vectors", 20, "easy"],
      [2, "Networking", "TCP/IP, DNS, HTTP/HTTPS analysis using Wireshark — complete 5 packet captures", 25, "easy"],
      [3, "Linux for Security", "Kali Linux setup, basic commands, and 10 network scanning exercises", 25, "medium"],
      [4, "OWASP Top 10", "Research, document, and demonstrate each of the 10 OWASP vulnerabilities", 30, "medium"],
      [5, "Web App Security", "Find and document vulnerabilities in DVWA — a legal and safe practice lab", 35, "medium"],
      [6, "Cryptography", "Implement AES encryption and RSA key exchange in Python", 35, "hard"],
      [7, "Ethical Hacking", "Nmap reconnaissance plus vulnerability assessment on a controlled practice lab", 40, "hard"],
      [8, "Social Engineering", "Phishing email analysis and defensive countermeasures documentation", 40, "hard"],
      [9, "Malware Analysis", "Static malware analysis on sandboxed samples using safe tooling", 45, "hard"],
      [10, "Incident Response", "Create a complete incident response plan for a fictional company scenario", 45, "expert"],
      [11, "CTF Challenge", "Complete a beginner CTF on TryHackMe — submit the flag with a full write-up", 55, "expert"],
      [12, "Final Project", "Full penetration testing report on an authorised practice target", 100, "expert"],
    ],
    "6months": [
      [1, "Security Fundamentals", "Write a detailed report on CIA Triad, common attack types, and threat vectors", 20, "easy"],
      [2, "Networking", "TCP/IP, DNS, HTTP/HTTPS analysis using Wireshark", 25, "easy"],
      [3, "Linux for Security", "Kali Linux setup, commands, and network scanning exercises", 25, "medium"],
      [4, "OWASP Top 10", "Research, document, and demonstrate each OWASP vulnerability", 30, "medium"],
      [5, "Web App Security", "Find and document vulnerabilities in DVWA", 35, "medium"],
      [6, "Cryptography", "AES encryption and RSA key exchange in Python", 35, "hard"],
      [7, "Ethical Hacking", "Nmap reconnaissance and vulnerability assessment on a practice lab", 40, "hard"],
      [8, "Social Engineering", "Phishing analysis and defensive countermeasures", 40, "hard"],
      [9, "Malware Analysis", "Static malware analysis on sandboxed samples", 45, "hard"],
      [10, "Incident Response", "Complete incident response plan for a fictional company", 45, "expert"],
      [11, "CTF Challenge", "Complete a TryHackMe CTF and submit a full write-up", 55, "expert"],
      [12, "Final Project", "Full penetration testing report on an authorised target", 100, "expert"],
      [13, "Advanced Pentesting", "Metasploit framework exploitation on a controlled practice lab", 50, "expert"],
      [14, "Buffer Overflow", "Exploit a buffer overflow vulnerability on a sandboxed binary", 55, "expert"],
      [15, "Reverse Engineering", "Basic binary reverse engineering with Ghidra on safe sample files", 55, "expert"],
      [16, "Web App Pentesting", "Full OWASP test on DVWA — document all findings and remediation steps", 55, "expert"],
      [17, "Cloud Security", "Identify and fix misconfigurations in an AWS test account", 60, "expert"],
      [18, "Forensics Basics", "Digital forensics: analyse a disk image for evidence using forensic tools", 60, "expert"],
      [19, "Red Team", "Plan and execute a full red team exercise on a controlled lab network", 65, "expert"],
      [20, "Blue Team", "Build a detection rule in a SIEM for a specific attack pattern", 60, "expert"],
      [21, "Zero Trust", "Design a zero-trust architecture for a fictional company — document it fully", 60, "expert"],
      [22, "Threat Intelligence", "Write a threat intelligence report on a recent CVE with remediation steps", 55, "expert"],
      [23, "Capstone Planning", "Plan a full penetration test engagement: scope, methodology, tools, timeline", 55, "expert"],
      [24, "Final Capstone", "Complete penetration test report with full remediation plan and executive summary", 200, "expert"],
    ],
    "45days": [
      [1, "Fundamentals + Networking", "CIA Triad report plus Wireshark TCP/IP analysis", 27, "easy"],
      [2, "Linux + OWASP", "Kali Linux setup and exercises plus OWASP Top 10 documentation", 33, "medium"],
      [3, "Web Security + Crypto", "DVWA vulnerability findings plus AES/RSA implementation in Python", 38, "medium"],
      [4, "Hacking + Social Eng", "Nmap recon lab plus phishing email analysis and countermeasures", 44, "hard"],
      [5, "Malware + Incident Resp", "Static malware analysis plus a full incident response plan", 49, "hard"],
      [6, "CTF + Final Report", "Complete a TryHackMe CTF and write a full penetration testing report", 110, "expert"],
    ],
    "1month": [
      [1, "Security Fundamentals", "CIA Triad, attack types, and basic Wireshark network analysis", 25, "easy"],
      [2, "Linux + OWASP", "Kali Linux setup and OWASP Top 10 research and documentation", 30, "medium"],
      [3, "Web App Security", "DVWA vulnerability identification and AES encryption implementation", 35, "hard"],
      [4, "Final Mini Project", "Beginner CTF on TryHackMe with a full write-up and lessons learned", 75, "hard"],
    ],
  },
  "Flutter Development": {
    "3months": [
      [1, "Flutter Setup", "Install Flutter, run your first app, and document the complete widget tree structure", 20, "easy"],
      [2, "Widgets", "Build 10 UI screens using fundamental Flutter widgets: Text, Container, ListView, Card", 25, "easy"],
      [3, "Layouts", "Build 5 responsive layouts using Row, Column, Stack, and Expanded widgets", 25, "easy"],
      [4, "Navigation", "Multi-screen app with named routes, Navigator, and data passing between screens", 30, "medium"],
      [5, "State Management", "Build a shopping cart application using the Provider state management package", 30, "medium"],
      [6, "API Integration", "Connect a Flutter app to a public REST API and display live data", 35, "medium"],
      [7, "Firebase", "Firebase Auth and Firestore in Flutter: build a full note-taking application", 40, "hard"],
      [8, "Animations", "Add page transitions, micro-animations, and Hero animations to your app", 40, "hard"],
      [9, "Local Storage", "SharedPreferences and SQLite: build a persistent offline-first application", 40, "hard"],
      [10, "Push Notifications", "Firebase push notifications with background and foreground handling", 45, "hard"],
      [11, "Mini Project", "Full Flutter app with authentication, API integration, and local database storage", 55, "expert"],
      [12, "Final Project", "Publish your Flutter app to Google Play Store or TestFlight for iOS", 100, "expert"],
    ],
    "6months": [
      [1, "Flutter Setup", "Install Flutter, run your first app, and document the widget tree", 20, "easy"],
      [2, "Widgets", "Build 10 UI screens using fundamental Flutter widgets", 25, "easy"],
      [3, "Layouts", "Build 5 responsive layouts", 25, "easy"],
      [4, "Navigation", "Multi-screen app with named routes and data passing", 30, "medium"],
      [5, "State Management", "Shopping cart app using Provider", 30, "medium"],
      [6, "API Integration", "Connect a Flutter app to a public REST API", 35, "medium"],
      [7, "Firebase", "Firebase Auth and Firestore in Flutter", 40, "hard"],
      [8, "Animations", "Page transitions, micro-animations, and Hero animations", 40, "hard"],
      [9, "Local Storage", "SharedPreferences and SQLite offline-first app", 40, "hard"],
      [10, "Push Notifications", "Firebase push notifications with background and foreground handling", 45, "hard"],
      [11, "Mini Project", "Full Flutter app with auth, API, and local database", 55, "expert"],
      [12, "Final Project", "Publish to Play Store or TestFlight", 100, "expert"],
      [13, "Advanced State", "Riverpod: replace Provider with Riverpod in an existing Flutter app", 45, "hard"],
      [14, "Bloc Pattern", "Implement BLoC architecture for a complex feature in the app", 50, "expert"],
      [15, "Platform Channels", "Write a native platform channel to access device sensors", 55, "expert"],
      [16, "Custom Paint", "Build custom charts and graphics using the CustomPainter API", 50, "expert"],
      [17, "Offline First", "Offline-first app architecture using Hive with sync-on-reconnect logic", 55, "expert"],
      [18, "Flutter Web", "Adapt the mobile application to also run correctly on Flutter Web", 55, "expert"],
      [19, "Desktop", "Build a Flutter desktop application for macOS or Windows", 60, "expert"],
      [20, "Performance", "Profile and fix jank in a Flutter app using Flutter DevTools", 55, "expert"],
      [21, "Testing", "Full widget and integration test suite for the Flutter application", 55, "expert"],
      [22, "CI/CD", "Fastlane and GitHub Actions: automated deployment to Play Store", 60, "expert"],
      [23, "Capstone Planning", "Plan a complete Flutter app for a real-world use case with full documentation", 55, "expert"],
      [24, "Final Capstone", "Complete Flutter app published to Play Store and deployed to Flutter Web", 200, "expert"],
    ],
    "45days": [
      [1, "Setup + Widgets + Layouts", "Install Flutter, build 5 UI screens, and create 3 responsive layouts", 27, "easy"],
      [2, "Navigation + State", "Multi-screen navigation with named routes and a shopping cart using Provider", 33, "medium"],
      [3, "API + Firebase", "REST API integration and Firebase Auth/Firestore note app in one project", 38, "medium"],
      [4, "Animations + Local Storage", "Hero animations and micro-transitions plus SQLite offline persistence", 44, "hard"],
      [5, "Push Notifications + Mini", "Firebase push notifications and a full Flutter mini-project with all features", 49, "hard"],
      [6, "Final Project", "Publish complete Flutter app to Google Play Store or TestFlight", 110, "expert"],
    ],
    "1month": [
      [1, "Flutter Basics", "Install Flutter, build 5 screens using fundamental widgets", 25, "easy"],
      [2, "Navigation + State", "Multi-screen app with named routes and Provider state management", 30, "medium"],
      [3, "API + Firebase", "Connect to a REST API and set up Firebase Auth in the app", 35, "hard"],
      [4, "Final Mini Project", "Complete Flutter app with navigation, API, and Firebase deployed to TestFlight", 75, "hard"],
    ],
  },
  "Software Engineering": {
    "3months": [
      [1, "SE Fundamentals", "Write a report on SDLC, Agile, Scrum, and Kanban with a detailed comparison", 20, "easy"],
      [2, "Requirements", "Write a full Software Requirements Specification document for a sample application", 25, "easy"],
      [3, "System Design", "Design a URL shortener: architecture diagram with full component explanation", 25, "medium"],
      [4, "Design Patterns", "Implement Singleton, Factory, Observer, Strategy, and Decorator patterns", 30, "medium"],
      [5, "Clean Code", "Refactor a messy codebase following Uncle Bob's clean code principles", 30, "medium"],
      [6, "Version Control", "Advanced Git: branching strategy, code review guide, and PR templates", 30, "medium"],
      [7, "Testing", "TDD practice: write tests before implementing each feature in a project", 35, "hard"],
      [8, "Database Design", "Create ER diagrams and a fully normalised schema for a social media app", 35, "hard"],
      [9, "API Design", "RESTful principles and OpenAPI/Swagger specification for a complete application", 40, "hard"],
      [10, "DevOps Integration", "Set up CI/CD for a software project with monitoring basics", 40, "hard"],
      [11, "Mini Project", "Full SE lifecycle: SRS → design → code → tests → documentation", 55, "expert"],
      [12, "Final Project", "Working product with complete professional documentation and deployment", 100, "expert"],
    ],
    "6months": [
      [1, "SE Fundamentals", "Write a report on SDLC, Agile, Scrum, and Kanban", 20, "easy"],
      [2, "Requirements", "Write a full SRS document for a sample application", 25, "easy"],
      [3, "System Design", "Design a URL shortener architecture with diagrams", 25, "medium"],
      [4, "Design Patterns", "Implement 5 classic design patterns", 30, "medium"],
      [5, "Clean Code", "Refactor a messy codebase using clean code principles", 30, "medium"],
      [6, "Version Control", "Advanced Git: branching, code review, PR templates", 30, "medium"],
      [7, "Testing", "TDD practice: test-driven development for a feature set", 35, "hard"],
      [8, "Database Design", "ER diagrams and normalised schema for a social app", 35, "hard"],
      [9, "API Design", "RESTful API design with OpenAPI specification", 40, "hard"],
      [10, "DevOps Integration", "CI/CD setup with monitoring for a software project", 40, "hard"],
      [11, "Mini Project", "Full SE lifecycle: SRS to deployed working product", 55, "expert"],
      [12, "Final Project", "Working product with complete professional documentation", 100, "expert"],
      [13, "Distributed Systems", "Design a distributed cache system with full documentation and architecture diagrams", 50, "expert"],
      [14, "Message Queues", "Implement a task queue system using RabbitMQ or BullMQ", 55, "expert"],
      [15, "Event-Driven Design", "Redesign a monolith feature using event-driven architecture patterns", 55, "expert"],
      [16, "API Gateway", "Set up Kong or AWS API Gateway with rate limiting and authentication", 55, "expert"],
      [17, "Code Review Practice", "Conduct 3 formal code reviews with written reports covering quality and patterns", 50, "hard"],
      [18, "Technical Debt", "Identify, document, and propose remediation for technical debt in a codebase", 50, "hard"],
      [19, "Observability", "Add structured logging and distributed tracing to a production application", 60, "expert"],
      [20, "Chaos Engineering", "Run chaos experiments using Chaos Monkey on a test system", 60, "expert"],
      [21, "SRE Basics", "Define SLIs, SLOs, and error budgets for a real service — document them fully", 55, "expert"],
      [22, "Architecture Review", "Full architecture review document for an existing system with improvement proposals", 60, "expert"],
      [23, "Capstone Planning", "Design the complete architecture for a scalable SaaS product", 55, "expert"],
      [24, "Final Capstone", "Complete system with architecture doc, working code, tests, and full documentation", 200, "expert"],
    ],
    "45days": [
      [1, "Fundamentals + Requirements", "SDLC/Agile report plus a full SRS document for a sample app", 27, "easy"],
      [2, "System Design + Patterns", "URL shortener architecture plus 5 design pattern implementations", 33, "medium"],
      [3, "Clean Code + Version Control", "Codebase refactoring plus advanced Git branching workflow", 33, "medium"],
      [4, "Testing + DB Design", "TDD practice plus ER diagram and normalised database schema", 38, "hard"],
      [5, "API Design + DevOps", "OpenAPI specification plus CI/CD pipeline setup", 44, "hard"],
      [6, "Mini + Final Project", "Full SE lifecycle from SRS to deployed working product", 110, "expert"],
    ],
    "1month": [
      [1, "SE Fundamentals", "SDLC/Agile/Scrum report and a full SRS document", 25, "easy"],
      [2, "Design + Patterns", "System design diagram plus 3 design pattern implementations", 30, "medium"],
      [3, "Testing + Clean Code", "TDD for a small feature and refactoring using clean code principles", 35, "hard"],
      [4, "Final Mini Project", "Complete working product with SRS, design doc, code, tests, and README", 75, "hard"],
    ],
  },
  "Business Analyst": {
    "3months": [
      [1, "TEN Business Model", "Analyse TEN's business model and write a stakeholder analysis document", 20, "easy"],
      [2, "Stakeholder Analysis", "Map all stakeholders, their needs, and influence on the TEN platform", 25, "easy"],
      [3, "Market Research", "Conduct primary and secondary market research for a chosen industry", 25, "medium"],
      [4, "Competitor Analysis", "Detailed competitor analysis using Porter's Five Forces and SWOT", 30, "medium"],
      [5, "Data Collection", "Design and execute a survey, then clean and organise the collected data", 30, "medium"],
      [6, "Excel Analysis", "Analyse business data using Excel: pivot tables, VLOOKUP, trend analysis", 35, "medium"],
      [7, "Dashboard Creation", "Build a business intelligence dashboard using Excel or Google Sheets", 35, "hard"],
      [8, "Problem Identification", "Identify 3 critical business problems and document root cause analysis", 40, "hard"],
      [9, "Revenue Analysis", "Analyse revenue streams, model growth scenarios, and identify bottlenecks", 40, "hard"],
      [10, "Financial Modelling", "Build a 3-year financial model with revenue, cost, and profit projections", 45, "hard"],
      [11, "Business Improvement Strategy", "Develop a complete business improvement strategy based on your analysis", 50, "expert"],
      [12, "Final Presentation", "Create and present a professional business strategy deck with data-backed recommendations", 100, "expert"],
    ],
    "6months": [
      [1, "TEN Business Model", "Analyse TEN's business model and write a stakeholder analysis document", 20, "easy"],
      [2, "Stakeholder Analysis", "Map all stakeholders, their needs, and influence", 25, "easy"],
      [3, "Market Research", "Primary and secondary market research for a chosen industry", 25, "medium"],
      [4, "Competitor Analysis", "Porter's Five Forces and SWOT analysis", 30, "medium"],
      [5, "Data Collection", "Survey design, data collection, and cleaning", 30, "medium"],
      [6, "Excel Analysis", "Business data analysis using Excel pivot tables and trend analysis", 35, "medium"],
      [7, "Dashboard Creation", "Build a BI dashboard using Excel or Google Sheets", 35, "hard"],
      [8, "Problem Identification", "Identify business problems and document root cause analysis", 40, "hard"],
      [9, "Revenue Analysis", "Revenue stream analysis and growth scenario modelling", 40, "hard"],
      [10, "Financial Modelling", "3-year financial model with projections", 45, "hard"],
      [11, "Business Improvement", "Complete business improvement strategy", 50, "expert"],
      [12, "Final Presentation", "Professional business strategy deck and presentation", 100, "expert"],
      [13, "Advanced Data Analysis", "Deep dive into the business from Month 3 — add SQL querying and advanced Excel modelling", 50, "expert"],
      [14, "Process Optimisation", "Map current business processes and redesign them for efficiency and scalability", 50, "expert"],
      [15, "Advanced Financial Modelling", "Build a dynamic financial model with scenarios: base, optimistic, pessimistic", 55, "expert"],
      [16, "Strategic Framework", "Apply BCG Matrix and Ansoff Matrix to a real company and document findings", 55, "expert"],
      [17, "Cross-Domain Data Science", "Apply basic data science and visualisation techniques to a real business dataset", 55, "expert"],
      [18, "Customer Journey Mapping", "Map the full customer journey for a product and identify drop-off points", 55, "expert"],
      [19, "KPI Framework", "Design a complete KPI framework for a business unit with tracking dashboards", 55, "expert"],
      [20, "Business Case Writing", "Write a formal business case document for a new initiative with ROI analysis", 55, "expert"],
      [21, "Capstone Planning", "Plan a complete business analysis project end-to-end — scope, data sources, deliverables", 55, "expert"],
      [22, "Capstone Execution", "Execute the planned analysis — data collection, modelling, and findings", 55, "expert"],
      [23, "Capstone Review", "Refine the capstone based on peer and mentor feedback", 55, "expert"],
      [24, "Final Capstone", "Professional-grade business analysis deliverable with presentation and documentation", 200, "expert"],
    ],
    "45days": [
      [1, "Business Model + Stakeholders", "TEN business model analysis and full stakeholder mapping document", 22, "easy"],
      [2, "Market + Competitor Research", "Industry market research and Porter's Five Forces competitor analysis", 27, "medium"],
      [3, "Data Collection + Excel", "Survey design, data collection, and Excel pivot table analysis", 33, "medium"],
      [4, "Dashboard + Problem ID", "BI dashboard creation and root cause analysis of 3 business problems", 38, "hard"],
      [5, "Revenue + Financial Modelling", "Revenue stream analysis and a 3-year financial projection model", 44, "hard"],
      [6, "Strategy + Presentation", "Business improvement strategy and final presentation deck", 110, "expert"],
    ],
    "1month": [
      [1, "Business Model + Market", "TEN business model analysis and market research for a chosen sector", 25, "easy"],
      [2, "Data + Excel Analysis", "Data collection, cleaning, and analysis using Excel pivot tables", 30, "medium"],
      [3, "Dashboard + Insights", "Build a BI dashboard and document 5 key business insights", 35, "hard"],
      [4, "Final Presentation", "Data-backed business strategy presentation with recommendations", 75, "hard"],
    ],
  },
  "Venture Capital": {
    "3months": [
      [1, "VC Fundamentals", "Write a comprehensive report on VC fundamentals and the startup lifecycle stages", 20, "easy"],
      [2, "Startup Lifecycle", "Map the full lifecycle of a startup from ideation to exit with case studies", 25, "easy"],
      [3, "Business Models", "Analyse 5 different SaaS and marketplace business models with revenue breakdowns", 25, "medium"],
      [4, "Market Sizing", "TAM/SAM/SOM analysis for 3 different startup ideas", 30, "medium"],
      [5, "Deal Sourcing", "Document a deal sourcing process: channels, criteria, and screening framework", 30, "medium"],
      [6, "Competitive Analysis", "Deep competitive analysis of a startup against 5 competitors", 35, "medium"],
      [7, "Valuation Methods", "Apply DCF, comparable companies, and Berkus methods to value a startup", 35, "hard"],
      [8, "Due Diligence", "Conduct a simulated due diligence on a startup — technical, legal, market", 40, "hard"],
      [9, "Term Sheets", "Analyse and draft a term sheet with key VC clauses and investor protections", 40, "hard"],
      [10, "Portfolio Strategy", "Design a VC portfolio strategy: sector focus, stage, check sizes, return targets", 45, "hard"],
      [11, "Exit Strategies", "Research and document exit strategies: IPO, M&A, secondary — with case studies", 50, "expert"],
      [12, "Investment Committee Sim", "Simulate an investment committee — pitch a startup, defend your thesis, answer objections", 100, "expert"],
    ],
    "6months": [
      [1, "VC Fundamentals", "VC fundamentals and startup lifecycle stages report", 20, "easy"],
      [2, "Startup Lifecycle", "Full startup lifecycle map with case studies", 25, "easy"],
      [3, "Business Models", "Analyse 5 business models with revenue breakdowns", 25, "medium"],
      [4, "Market Sizing", "TAM/SAM/SOM analysis for 3 startup ideas", 30, "medium"],
      [5, "Deal Sourcing", "Deal sourcing channels, criteria, and screening framework", 30, "medium"],
      [6, "Competitive Analysis", "Deep competitor analysis for a startup", 35, "medium"],
      [7, "Valuation Methods", "DCF, comparable companies, and Berkus valuation methods", 35, "hard"],
      [8, "Due Diligence", "Simulated due diligence on a startup", 40, "hard"],
      [9, "Term Sheets", "Analyse and draft a VC term sheet", 40, "hard"],
      [10, "Portfolio Strategy", "Design a VC portfolio strategy", 45, "hard"],
      [11, "Exit Strategies", "Exit strategy research and documentation", 50, "expert"],
      [12, "Investment Committee Sim", "Full investment committee simulation", 100, "expert"],
      [13, "Advanced Deal Analysis", "Full end-to-end deal analysis on a real startup pitch deck from a public source", 50, "expert"],
      [14, "Cap Table Modelling", "Build a cap table model through a Series A and B with dilution analysis", 55, "expert"],
      [15, "Fund Economics", "Model VC fund economics: management fees, carried interest, TVPI, DPI", 55, "expert"],
      [16, "Portfolio Management", "Design a portfolio monitoring framework with KPIs and board reporting templates", 55, "expert"],
      [17, "Real Startup Pitch", "Model a real startup pitch end-to-end — market, team, financials, ask", 55, "expert"],
      [18, "Cross-Domain: Fintech", "Deep dive into Fintech vertical — trends, players, regulatory landscape, deal flow", 55, "expert"],
      [19, "LP Reporting", "Create an investor (LP) update report with fund performance and portfolio updates", 55, "expert"],
      [20, "Emerging Markets VC", "Research and document VC opportunities in an emerging market (India, SEA, Africa)", 55, "expert"],
      [21, "Capstone Planning", "Plan a complete investment thesis — sector, geography, stage, and fund structure", 55, "expert"],
      [22, "Capstone Execution", "Build the financial models and documentation for your investment thesis", 55, "expert"],
      [23, "Capstone Review", "Present and defend the thesis to a panel — incorporate feedback", 55, "expert"],
      [24, "Final Capstone", "Full investment thesis document with pitch deck, cap table, and fund model", 200, "expert"],
    ],
    "45days": [
      [1, "VC Fundamentals + Lifecycle", "VC basics and full startup lifecycle with case studies", 22, "easy"],
      [2, "Business Models + Market Sizing", "5 business model analyses and TAM/SAM/SOM for 2 startup ideas", 27, "medium"],
      [3, "Deal Sourcing + Competitor", "Deal sourcing framework and deep competitor analysis for a startup", 33, "medium"],
      [4, "Valuation + Due Diligence", "DCF valuation and simulated due diligence on a startup", 38, "hard"],
      [5, "Term Sheets + Portfolio", "Draft a term sheet and design a VC portfolio strategy", 44, "hard"],
      [6, "Exit + Investment Committee", "Exit strategy research and full investment committee simulation", 110, "expert"],
    ],
    "1month": [
      [1, "VC Fundamentals", "VC basics, startup lifecycle, and business model analysis", 25, "easy"],
      [2, "Market + Deal Analysis", "Market sizing and deal sourcing framework for a chosen sector", 30, "medium"],
      [3, "Valuation + Due Diligence", "Apply a valuation method and simulate a due diligence checklist", 35, "hard"],
      [4, "Final Investment Memo", "Write a one-page investment memo for a startup you have analysed", 75, "hard"],
    ],
  },
  "Space Research": {
    "3months": [
      [1, "Space History", "Write a comprehensive report on the history of space exploration and key milestones", 20, "easy"],
      [2, "Solar System", "Comparative study of the 8 planets: composition, atmosphere, and habitability", 25, "easy"],
      [3, "Orbital Mechanics", "Explain orbital mechanics: Kepler's laws, orbital insertion, and transfer orbits", 25, "medium"],
      [4, "Spacecraft Systems", "Document the subsystems of a spacecraft: propulsion, power, communication, ADCS", 30, "medium"],
      [5, "Remote Sensing", "Analyse satellite imagery using open data — identify geographical features", 30, "medium"],
      [6, "Satellite Data", "Download and process real satellite data from NASA or ESA open portals", 35, "medium"],
      [7, "Astrophysics", "Research the life cycle of stars and stellar classification — document with diagrams", 35, "hard"],
      [8, "Mission Planning", "Design a mission plan for a lunar or Mars mission: objectives, trajectory, budget", 40, "hard"],
      [9, "Space Robotics", "Research space robotics: types, applications, and current missions", 40, "hard"],
      [10, "Planetary Science", "Analyse data from a planetary science mission and write an in-depth findings report", 45, "hard"],
      [11, "Research Proposal", "Write a formal research proposal for a space science question of your choice", 50, "expert"],
      [12, "Capstone", "Complete a space research paper on your chosen topic with citations and data analysis", 100, "expert"],
    ],
    "6months": [
      [1, "Space History", "History of space exploration and key milestones report", 20, "easy"],
      [2, "Solar System", "Comparative study of the 8 planets", 25, "easy"],
      [3, "Orbital Mechanics", "Kepler's laws, orbital insertion, and transfer orbits", 25, "medium"],
      [4, "Spacecraft Systems", "Document spacecraft subsystems", 30, "medium"],
      [5, "Remote Sensing", "Satellite imagery analysis using open data", 30, "medium"],
      [6, "Satellite Data", "Process real satellite data from NASA or ESA portals", 35, "medium"],
      [7, "Astrophysics", "Life cycle of stars and stellar classification", 35, "hard"],
      [8, "Mission Planning", "Design a lunar or Mars mission plan", 40, "hard"],
      [9, "Space Robotics", "Space robotics research: types, applications, missions", 40, "hard"],
      [10, "Planetary Science", "Planetary mission data analysis and findings report", 45, "hard"],
      [11, "Research Proposal", "Formal research proposal for a space science question", 50, "expert"],
      [12, "Capstone", "Space research paper with citations and data analysis", 100, "expert"],
      [13, "Advanced Orbital Mechanics", "Advanced topics: Hohmann transfers, gravity assists, Lagrange points", 50, "expert"],
      [14, "Exoplanet Research", "Analyse exoplanet detection methods and evaluate habitability data from Kepler/TESS", 55, "expert"],
      [15, "Space Policy & Law", "Research and document international space law and policy frameworks", 55, "expert"],
      [16, "Commercial Space", "Analysis of the commercial space sector: SpaceX, Blue Origin, ISRO, and new entrants", 55, "expert"],
      [17, "Astrobiology", "Research astrobiology: conditions for life, Mars habitability, ocean worlds", 55, "expert"],
      [18, "Space Instrumentation", "Study and document scientific instruments on a current space mission", 55, "expert"],
      [19, "Data Analysis Project", "Download and analyse a NASA open dataset — produce visualisations and findings", 55, "expert"],
      [20, "Future of Space", "Research and document the future of space exploration for the next 50 years", 55, "expert"],
      [21, "Capstone Planning", "Plan a complete space research project: question, data sources, methodology", 55, "expert"],
      [22, "Capstone Research", "Execute the research — data collection, analysis, and preliminary findings", 55, "expert"],
      [23, "Capstone Writing", "Write the full research paper draft with citations", 55, "expert"],
      [24, "Final Capstone", "Polished space research paper ready for submission to an academic forum", 200, "expert"],
    ],
    "45days": [
      [1, "Space History + Solar System", "History of space exploration and comparative planetary science report", 22, "easy"],
      [2, "Orbital Mechanics + Spacecraft", "Orbital mechanics fundamentals and spacecraft subsystems documentation", 27, "medium"],
      [3, "Remote Sensing + Satellite Data", "Satellite imagery analysis and real open-data processing from NASA", 33, "medium"],
      [4, "Astrophysics + Mission Planning", "Stellar lifecycle research and a lunar or Mars mission design", 38, "hard"],
      [5, "Robotics + Planetary Science", "Space robotics research and planetary mission data analysis", 44, "hard"],
      [6, "Research Proposal + Capstone", "Write a formal research proposal and complete a full space research paper", 110, "expert"],
    ],
    "1month": [
      [1, "Space Fundamentals", "Space history, solar system comparison, and orbital mechanics basics", 25, "easy"],
      [2, "Spacecraft + Remote Sensing", "Spacecraft subsystems and satellite data analysis using open tools", 30, "medium"],
      [3, "Astrophysics + Mission", "Stellar classification and a basic mission design for a planetary target", 35, "hard"],
      [4, "Final Research Paper", "Complete a short space research paper with citations and data visualisations", 75, "hard"],
    ],
  },
  "Vibe Coding": {
    "3months": [
      [1, "Vibe Coding Intro", "Explore AI coding assistants: Cursor, GitHub Copilot, and Replit — document what each does best", 20, "easy"],
      [2, "AI Coding Assistants", "Build a simple web page entirely using AI prompts — document every prompt and output", 25, "easy"],
      [3, "UI/UX Basics", "Learn core UI/UX principles and redesign 3 real-world interfaces with explanation", 25, "medium"],
      [4, "No-Code Tools", "Build a working landing page using no-code tools like Webflow or Framer", 30, "medium"],
      [5, "APIs Basics", "Connect to a public API using no-code tools and display live data on a webpage", 30, "medium"],
      [6, "Automation Scripts", "Build 3 automation scripts using AI assistance: email sorter, data cleaner, file organiser", 35, "medium"],
      [7, "AI-Powered Web App", "Build a simple AI-powered web app using an LLM API and a frontend framework", 40, "hard"],
      [8, "Advanced AI Web App", "Add user accounts, a database, and a dashboard to the AI-powered web app", 40, "hard"],
      [9, "MVP Building", "Define a real problem and build an MVP in 1 week using AI tools and rapid prototyping", 45, "hard"],
      [10, "MVP Iteration", "Get 5 real user feedback responses on your MVP and iterate on the top 3 findings", 45, "hard"],
      [11, "Deployment", "Deploy your MVP to a live URL with a proper domain, HTTPS, and basic analytics", 50, "hard"],
      [12, "Final Capstone", "Complete, deployed, and documented product — present it with a demo video", 100, "expert"],
    ],
    "6months": [
      [1, "Vibe Coding Intro", "Explore AI coding assistants and document use cases for each", 20, "easy"],
      [2, "AI Coding Assistants", "Build a web page using only AI prompts — document every interaction", 25, "easy"],
      [3, "UI/UX Basics", "UI/UX principles and 3 interface redesigns with reasoning", 25, "medium"],
      [4, "No-Code Tools", "Landing page built with Webflow or Framer", 30, "medium"],
      [5, "APIs Basics", "Live data on a webpage using no-code API tools", 30, "medium"],
      [6, "Automation Scripts", "3 automation scripts built with AI assistance", 35, "medium"],
      [7, "AI-Powered Web App", "AI-powered web app using LLM API", 40, "hard"],
      [8, "Advanced AI Web App", "Add accounts, database, and dashboard to the AI web app", 40, "hard"],
      [9, "MVP Building", "Build an MVP in 1 week using AI and rapid prototyping", 45, "hard"],
      [10, "MVP Iteration", "User testing and 3 iterations based on feedback", 45, "hard"],
      [11, "Deployment", "Deploy MVP to live URL with domain and analytics", 50, "hard"],
      [12, "Final Capstone v1", "Deployed product with demo video and documentation", 100, "expert"],
      [13, "Growth Hacking", "Implement 3 growth hacking strategies for the deployed product and measure results", 50, "expert"],
      [14, "Monetisation", "Add a payment flow using Stripe or Razorpay to the existing product", 55, "expert"],
      [15, "Advanced AI Features", "Add AI-powered features: search, recommendations, or generation to the product", 55, "expert"],
      [16, "Product Analytics", "Integrate product analytics: Mixpanel or PostHog — track key user events", 55, "expert"],
      [17, "Mobile Version", "Build a mobile-responsive or React Native version of the existing web product", 55, "expert"],
      [18, "Team Building Simulation", "Simulate onboarding a co-founder: document handoff process and code documentation", 55, "expert"],
      [19, "SaaS Architecture", "Redesign the product as a multi-tenant SaaS — document the architecture changes", 55, "expert"],
      [20, "Launch Strategy", "Create a full product launch strategy: marketing, distribution, and metrics", 55, "expert"],
      [21, "Capstone Planning", "Plan a new product from scratch: problem, solution, tech stack, MVP scope", 55, "expert"],
      [22, "Capstone Build", "Build the planned product using AI-first development methodology", 55, "expert"],
      [23, "Capstone Launch Prep", "Prepare for launch: testing, documentation, landing page, and marketing content", 55, "expert"],
      [24, "Final Capstone", "Live product with real users, documentation, demo video, and launch post", 200, "expert"],
    ],
    "45days": [
      [1, "AI Coding Intro + UI/UX", "Explore AI coding tools and redesign 2 interfaces using UI/UX principles", 22, "easy"],
      [2, "No-Code + APIs", "Build a landing page with no-code tools and add live API data to it", 27, "medium"],
      [3, "Automation + AI Web App", "3 automation scripts and a basic AI-powered web application", 38, "medium"],
      [4, "MVP Building + Iteration", "Build an MVP and iterate based on user feedback", 44, "hard"],
      [5, "Deployment + Analytics", "Deploy the MVP with live URL and set up basic product analytics", 49, "hard"],
      [6, "Final Product + Demo", "Polished live product with a demo video and public documentation", 110, "expert"],
    ],
    "1month": [
      [1, "AI Tools + UI/UX", "Explore AI coding assistants and build a page using only AI prompts", 25, "easy"],
      [2, "No-Code + API", "No-code landing page with live API data integration", 30, "medium"],
      [3, "AI Web App", "Simple AI-powered web application using an LLM API", 40, "hard"],
      [4, "Final MVP", "Deployed MVP with live URL, demo video, and GitHub documentation", 75, "hard"],
    ],
  },
  "HR Management": {
    "3months": [
      [1, "HR Fundamentals", "Write a report on the 6 core HR functions and how they interact with each other", 20, "easy"],
      [2, "Recruitment Process", "Design a complete end-to-end recruitment workflow diagram with all stages", 25, "easy"],
      [3, "Job Descriptions", "Write 3 detailed JDs for roles: Developer, Designer, and Marketing Manager", 25, "easy"],
      [4, "Interviewing", "Create a structured interview scorecard and 20 HR screening questions for a tech role", 30, "medium"],
      [5, "Onboarding", "Design a comprehensive 30-day onboarding plan for a new software engineer hire", 30, "medium"],
      [6, "Employee Engagement", "Create a 15-question engagement survey and analyse the fictional results with insights", 30, "medium"],
      [7, "Performance Management", "Design a quarterly performance review framework with a rating rubric", 35, "hard"],
      [8, "HR Analytics", "Analyse a dataset: calculate attrition rate, average tenure, and headcount trend", 35, "hard"],
      [9, "Labour Law", "Summarise 5 key Indian labour laws with practical implications for employers", 40, "hard"],
      [10, "Training & Development", "Design a 4-week training programme for a specific role in a startup", 40, "hard"],
      [11, "Policy Writing", "Write a complete HR policy document covering leave policy and code of conduct", 45, "hard"],
      [12, "Final Project", "Compile a complete HR Operations Manual for a fictional 20-person startup", 100, "expert"],
    ],
    "6months": [
      [1, "HR Fundamentals", "Write a report on the 6 core HR functions", 20, "easy"],
      [2, "Recruitment Process", "Complete end-to-end recruitment workflow diagram", 25, "easy"],
      [3, "Job Descriptions", "3 detailed JDs for Developer, Designer, Marketing Manager", 25, "easy"],
      [4, "Interviewing", "Structured interview scorecard and 20 HR screening questions", 30, "medium"],
      [5, "Onboarding", "30-day onboarding plan for a software engineer", 30, "medium"],
      [6, "Employee Engagement", "15-question engagement survey with analysis", 30, "medium"],
      [7, "Performance Management", "Quarterly performance review framework with rubric", 35, "hard"],
      [8, "HR Analytics", "Analyse attrition, tenure, and headcount data", 35, "hard"],
      [9, "Labour Law", "5 key Indian labour laws with practical implications", 40, "hard"],
      [10, "Training & Development", "4-week training programme for a startup role", 40, "hard"],
      [11, "Policy Writing", "Leave policy and code of conduct document", 45, "hard"],
      [12, "Final Project", "HR Operations Manual for a 20-person startup", 100, "expert"],
      [13, "Advanced Talent Acquisition", "Build a full employer branding strategy and sourcing pipeline for a growing company", 50, "expert"],
      [14, "Compensation & Benefits", "Design a compensation structure and benefits package for a 50-person startup", 55, "expert"],
      [15, "Diversity & Inclusion", "Create a DEI strategy and implementation roadmap for an organisation", 55, "expert"],
      [16, "HR Technology", "Evaluate 3 HRMS platforms and write a recommendation report", 55, "expert"],
      [17, "People Operations", "Design a complete people operations system for a 100-person company", 55, "expert"],
      [18, "HR Strategy", "Develop a 1-year HR strategy aligned with business goals for a growth-stage startup", 55, "expert"],
      [19, "Employee Experience", "Map and improve the full employee experience lifecycle from hiring to exit", 55, "expert"],
      [20, "HR Metrics & ROI", "Calculate HR ROI metrics: cost-per-hire, time-to-fill, retention rate, eNPS", 55, "expert"],
      [21, "Capstone Planning", "Plan a complete HR transformation project for a fictional organisation", 55, "expert"],
      [22, "Capstone Execution", "Build all HR systems, policies, and frameworks for the planned project", 55, "expert"],
      [23, "Capstone Review", "Refine the HR transformation plan based on structured feedback", 55, "expert"],
      [24, "Final Capstone", "Complete HR Operations Manual for a 100-person company — professional-grade deliverable", 200, "expert"],
    ],
    "45days": [
      [1, "HR Fundamentals + Recruitment", "6 core HR functions report plus a complete recruitment workflow diagram", 22, "easy"],
      [2, "JDs + Interviewing", "3 job descriptions plus a structured interview scorecard", 27, "easy"],
      [3, "Onboarding + Engagement", "30-day onboarding plan plus a 15-question employee engagement survey", 33, "medium"],
      [4, "Performance + Analytics", "Performance review framework plus HR data analysis — attrition and headcount", 38, "hard"],
      [5, "Labour Law + Training", "5 key labour law summaries plus a 4-week training programme design", 44, "hard"],
      [6, "Policy + HR Manual", "Full HR policy document plus a complete HR Operations Manual", 110, "expert"],
    ],
    "1month": [
      [1, "HR Fundamentals + Recruitment", "6 HR functions report, recruitment workflow, and 2 job descriptions", 25, "easy"],
      [2, "Interviewing + Onboarding", "Structured interview scorecard plus a 30-day onboarding plan", 30, "medium"],
      [3, "Performance + Analytics", "Performance review framework and basic HR data analysis", 35, "hard"],
      [4, "Final HR Manual", "Complete HR Operations Manual for a fictional 10-person startup", 75, "hard"],
    ],
  },
};

export const DOMAINS = Object.keys(CURRICULUM);
